name: Bug Report
description: I saw something that should not have happened and I'd like to report it
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before posting, be sure that it's not a duplicate of any previous posted issues by using the search function.
        Please note that we do not support outdated versions. Always use the latest stable release.
        Do not use this form for reporting issues related to traces. Use the 'Report traces bug' form.
  - type: dropdown
    id: category
    attributes:
      label: Scope
      description: Select the most appropriate category.
      options:
        - Core
        - General bot behavior
        - Vehicle bot behavior
        - Permission Manager
        - Configuration and registry
        - Telemetry
        - WebUI
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What happened and what should not have happened? Please also tell us how we can reproduce it, the more information we have, the faster and easier it is for us to fix this issue.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: What was expected?
      description: What should have happened instead?
      placeholder: What you should see instead.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce and test it?
      description: What is causing this issue? How can we reproduce it? If you have modified your configuration files, what did you modify?
      placeholder: I did ... then I did ... and that's what caused ...
    validations:
      required: true
  - type: textarea
    id: server-info
    attributes:
      label: Version of fun-bots and VU?
      description: What versions are you using? On what VU version happens this problem? Are you running any other mods?
      placeholder: fun-bots Release 2.4.0, updateBranch dev of VU
  - type: checkboxes
    id: terms
    attributes:
      label: I have checked the following... (if applicable)
      description: Before submitting this bug report, checkout the contributing guidelines and our code of conduct.
      options:
        - label: I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
          required: true
        - label: I have tested and reproduced this bug without any other mods besides fun-bots.
          required: false