name: publish vumm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish
        uses: BF3RM/vumm-action
        env:
          VUMM_TOKEN: ${{ secrets.VUMM_TOKEN }}
